### ISSUE TITLE
review digidem/mapeo repos for existing docs

### ISSUE THREAD

**Issue by todrobbins** [digidem/mapeo-docs#1]
Find usage examples, etc., from other repos and collect here

**Comment by todrobbins** [comment]
@karissa @gmaclennan @emjacobi, here's my first pass at collecting all of the Mapeo repositories. Am I missing any?

# Mapeo Ecosystem

## Apps
- [mapeo-desktop](https://github.com/digidem/mapeo-desktop): Mapping and monitoring in remote environments
- [mapeo-mobile](https://github.com/digidem/mapeo-mobile): Monitor and document the world around you
- [mapeo-apks-bucket-listing](https://github.com/digidem/mapeo-apks-bucket-listing): Listing of mapeo apk build files

## Configuration

- [mapeo-config-bengal](https://github.com/digidem/mapeo-config-bengal): Mapeo config for Bengal training

## Data
- [wao-export](https://github.com/digidem/wao-export): Export layers from Mapeo for Waorani maps

## Demos
- [mapeo-print-preview](https://github.com/digidem/mapeo-print-preview): Demo of web vector tiles for osm-p2p data.

## Documentation
- [mapeo-docs](https://github.com/digidem/mapeo-docs): Docs site for mapeo

## Modules
- [mapeo-components](https://github.com/digidem/mapeo-components)
- [mapeo-core](https://github.com/digidem/mapeo-core): Library for creating custom geo data and synchronizing via a peer to peer network
- [mapeo-server](https://github.com/digidem/mapeo-server): Mapping web server for managing observations, media, tiles, and various static files.
- [mapeo-openmaptiles](https://github.com/digidem/mapeo-openmaptiles): Lightweight map tiles for mapeo-mobile for global offline map
- [iD-mapeo](https://github.com/digidem/iD-mapeo): iD Editor for mapeo-desktop
- [mapeo-settings](https://github.com/digidem/mapeo-settings): Settings for Mapeo
- [mapeo-schema](https://github.com/digidem/mapeo-schema): Data schemas for mapeo data types
- [mapeo-styles](https://github.com/digidem/mapeo-styles): Default styles & tiles for mapeo backgrounds

## Utilities
- [mapeo-migrate](https://github.com/digidem/mapeo-migrate): Commandline tool for mapeo migrating databases from older formats to the latest.
- [mapeo-settings-builder](https://github.com/digidem/mapeo-settings-builder): Build presets and sprites for the Mapeo apps

**Comment by okdistribute** [comment]
i cleaned this up today!
