### ISSUE TITLE
Correct link to Mapeo Mac desktop version link on gitbook

### ISSUE THREAD

**Issue by psubhashish** [digidem/mapeo-docs#14]
Hi there, I was going through the [documentation](https://docs.mapeo.app/installation#install-on-mac) and found out that the the link to Mac version is outdated and the correct link would be https://www.digital-democracy.org/mapeo/ or https://www.digital-democracy.org/mapeo/download (for auto-prompt). Would appreciate if you could update the same. Thanks!

**Comment by arky** [comment]
Thanks for reporting @psubhashish 

I have changed the link to https://www.digital-democracy.org/mapeo/latest/mac

Fixed in https://app.gitbook.com/@digital-democracy/s/mapeo/~/drafts/-MZvmD1xZJFf5l3hSipc/@merged

**Comment by arky** [comment]
Fixed in https://app.gitbook.com/@digital-democracy/s/mapeo/~/drafts/-MZvmD1xZJFf5l3hSipc/@merged

**Comment by psubhashish** [comment]
Thanks much Arky!
