### ISSUE TITLE
Moving to gitbook.io

### ISSUE THREAD

**Issue by okdistribute** [digidem/mapeo-docs#9]
Gitbook will give us a free plan as a non-profit. 

I started putting it here: https://digital-democracy.gitbook.io/mapeo/

It has search & translations and seems overall better maintained than docusaurus.

Although it's a hosted platform, we can connect it with github and have control of the content in the form of the markdown files

**Comment by okdistribute** [comment]
todo to finish transition 
- [x] change the DNS in gitbook (you need the admin link, dm me for that) @gmaclennan 
- [x] e-mail gitbook with our non-profit status (i emailed sesoo, waiting for that)
- [x] update website if necessary

**Comment by gmaclennan** [comment]
@okdistribute I think it's good to sync with github, where do you think those docs should live? We could keep them here or move them into MD or MM repos?

**Comment by okdistribute** [comment]
I think they should be in their own repo as they are currently. digidem/mapeo-docs (or mapeo/docs), because they are deployed as a website

**Comment by okdistribute** [comment]
Next we need to import from gitbook to this repo

**Comment by okdistribute** [comment]
OK now this has been imported from gitbook.

Variants are stored on branches, for example the `spanish` branch is visible on the homepage. It is out of date.

**Comment by todrobbins** [comment]
Sorry I missed these messages @okdistribute! I would have gladly pitched in! Anything left to clean up?

**Comment by okdistribute** [comment]
@todrobbins yeah, thanks @todrobbins for the support! We probably could make internationalization easier. Right now someone would need to update the spanish branch of this github repository. I wonder if there's a way we can still use crowdin or transifex or something more user friendly with gitbook?

**Comment by gmaclennan** [comment]
Updated #5 with some ideas about how to do this.
